# Generated by Django 5.2 on 2025-04-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetime_secret_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secret',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
