# Generated by Django 5.2 on 2025-04-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onetime_secret_sharing_app', '0002_alter_secret_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='url',
            new_name='uri',
        ),
        migrations.AddField(
            model_name='secret',
            name='uri_secret',
            field=models.CharField(default='na', max_length=100),
            preserve_default=False,
        ),
    ]
