# Generated by Django 5.2 on 2025-04-21 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onetime_secret_sharing_app', '0003_rename_url_secret_uri_secret_uri_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secret',
            old_name='uri_secret',
            new_name='uri_random_text',
        ),
    ]
