# Generated by Django 5.2 on 2025-05-01 09:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_lite', '0005_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tweet_files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(blank=True, max_length=10)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='twitter_lite.tweet')),
            ],
            options={
                'verbose_name': 'Tweet File',
                'verbose_name_plural': 'Tweet Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
