# Generated by Django 5.1.4 on 2024-12-25 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_rename_user_userinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='User',
        ),
    ]
