# Generated by Django 5.1.4 on 2024-12-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_rename_userinfo_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
